version: "3.7"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: yarn start
    tty: true
    stdin_open: true
