FROM node:13-alpine

EXPOSE 3000

WORKDIR /usr/src/app

COPY . .

RUN yarn --silent
RUN yarn global add react-scripts --silent
ENV PATH /app/node_modules/.bin:$PATH

VOLUME /usr/src/app

CMD ["yarn", "start"]