version: "3.7"

services:
  server:
    depends_on:
      - db
    links:
      - db:db
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file: ./server/.env
    ports:
      - 4000:3000
    volumes:
      - ./server/src:/usr/bin/app/src

  db:
    image: mysql
    env_file: ./server/.env.docker-db

  client:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: yarn start
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    tty: true
    stdin_open: true
