version: "3.7"

services:
  server:
    depends_on:
      - db
    links:
      - db:db
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 4000:3000

  db:
    image: mysql
    env_file: ./.env.docker-db
